---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    type: db
    author: jeevan
spec:
  replicas: 2
  selector:
    matchLabels:
      type: db
  template:
    metadata:
      name: postgres-pod
      labels:
        type: db
    spec:
      containers:
        - name: mypostgres
          image: postgres
          env:
            - name: postgres_password
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: postgres_User
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: user
            - name: postgres_db
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: dbname
          volumeMounts:
             - name: postgres-volume
               mountPath: /var/lib/postgresql/data

      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim
...
